kind: pipeline
name: default

steps:
  - name: docker-to-hub
    image: thegeeklab/drone-docker-buildx:latest
    privileged: true
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      repo: bonny1992/informrr
      tags:
        - latest
        - ${DRONE_SOURCE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      platforms:
        - linux/amd64
        - linux/arm64
  - name: docker-to-quay
    image: thegeeklab/drone-docker-buildx:latest
    privileged: true
    settings:
      username:
        from_secret: QUAY_USER
      password:
        from_secret: QUAY_PASS
      registry: quay.io
      repo: quay.io/bonny1992/informrr
      tags:
        - latest
        - ${DRONE_SOURCE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      platforms:
        - linux/amd64
        - linux/arm64
  - name: docker-to-ghcr
    image: thegeeklab/drone-docker-buildx:latest
    privileged: true
    settings:
      username:
        from_secret: GHCR_USER
      password:
        from_secret: GITHUB_TOKEN
      registry: ghcr.io
      repo: ghcr.io/bonny1992/informrr
      tags:
        - latest
        - ${DRONE_SOURCE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      platforms:
        - linux/amd64
        - linux/arm64