kind: pipeline
name: default

steps:
  - name: docker
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      username:
        from_secret: QUAY_USER
      password:
        from_secret: QUAY_PASS
      registry: quay.io
      repo: bonny1992/informrr
      tags: latest
      platforms:
        - linux/amd64
        - linux/arm64/v8